@rem Update a file with the latest GIT revision information
@rem Input: takes the path to the file to update as a parameter
@rem Example:
@rem  update_revs.bat include/git_rev_data.h

set prefix="#define GIT_REV_DATA "
set revdata=unknown

echo // DO NOT EDIT THIS FILE. AUTOMATICALLY GENERATED > %1
echo | set /p=%prefix% >> %1
for /f %%i in ('git describe --tags --long') do set revdata=%%i
echo "%revdata%" >> %1

exit 0