#ifndef FX_DEVICE_DEFS_H
#define FX_DEVICE_DEFS_H

// field ids
#define FX_RIGID_DEVTYPE 0
#define FX_RIGID_DEVTID 1
#define FX_RIGID_STATETIME 2
#define FX_RIGID_ACCELX 3
#define FX_RIGID_ACCELY 4
#define FX_RIGID_ACCELZ 5
#define FX_RIGID_GYROX 6
#define FX_RIGID_GYROY   7
#define FX_RIGID_GYROZ 8
#define FX_RIGID_ENC_ANG 9
#define FX_RIGID_ENC_VEL 10
#define FX_RIGID_ENC_ACC 11
#define FX_RIGID_MOT_CURR 12
#define FX_RIGID_MOT_VOLT 13
#define FX_RIGID_BATT_VOLT 14
#define FX_RIGID_BATT_CURR 15
#define FX_RIGID_BATT_TEMP 16
#define FX_RIGID_BATT_STATUS 17
#define FX_RIGID_GEN_VAR_BASE 18
#define FX_RIGID_GEN_VAR_0 (FX_GEN_VAR_BASE + 0)
#define FX_RIGID_GEN_VAR_1 (FX_GEN_VAR_BASE + 1)
#define FX_RIGID_GEN_VAR_2 (FX_GEN_VAR_BASE + 2)
#define FX_RIGID_GEN_VAR_3 (FX_GEN_VAR_BASE + 3)
#define FX_RIGID_GEN_VAR_4 (FX_GEN_VAR_BASE + 4)
#define FX_RIGID_GEN_VAR_5 (FX_GEN_VAR_BASE + 5)
#define FX_RIGID_GEN_VAR_6 (FX_GEN_VAR_BASE + 6)
#define FX_RIGID_GEN_VAR_7 (FX_GEN_VAR_BASE + 7)
#define FX_RIGID_GEN_VAR_8 (FX_GEN_VAR_BASE + 8)
#define FX_RIGID_GEN_VAR_9 (FX_GEN_VAR_BASE + 9)

#endif // FX_DEVICE_DEFS_H
